name: Continous Integrations
on:
  push:
    branches:
      - develop
      - main

jobs:
  teste:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install

      - name: Run CI with Lefthook
        run: |
          yarn lefthook run ci-hook
    
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit testes:
            tests message: test passed successfully!
            
            Repository: ${{ github.repository }}
#      - name: Run test
#        run: |
#          yarn test-ci
